# identifiers.org Satellite docker-compose based development environment
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>

# NOTE - We can see circular dependencies over here, where link-checker dependes on the resolver, which depends on the
# resource recommender, which also depends on the resolver... Fortunately, what we are testing here is the resource
# recommender, and not the resolution API, we also know that the resolver only requires the recommender for resolving
# purposes, not for the current iteration of the insight API. Anyway, this is something that should be addressed in the
# future, we should try to avoid circular dependencies. In addition, for those unit tests that are testing resource
# recommender internals, no other services are needed, and the rest of the tests, e.g. integration tests, the resource
# recommender will run fully, so... let's see how it goes, hahaha!
version: "3"
services:
    link-checker:
        image: identifiersorg/cloud-ws-link-checker:1.0.1
        environment:
            - WS_LINK_CHECKER_CONFIG_REDIS_HOST=redis
            - WS_LINK_CHECKER_CONFIG_BACKEND_SERVICE_RESOLVER_HOST=resolver
        ports:
            - "8084:8084"
        depends_on:
            - resolver
            - redis
    resolver:
        image: identifiersorg/cloud-ws-resolver:1.0.3
        environment:
            - WS_RESOLVER_CONFIG_REDIS_HOST=redis
            - WS_RESOLVER_CONFIG_REDIS_PORT=6379
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_HOST=localhost
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_PORT=8083
            - WS_RESOLVER_JVM_MEMORY_MAX=1024m
            - WS_RESOLVER_CONFIG_APPLICATION_ACTIVE_PROFILE=development
        ports:
            - "8080:8080"
        depends_on:
            - redis
    redis:
        image: redis:4.0.8-alpine
        ports:
            - "6379:6379"
