# identifiers.org Satellite docker-compose based development environment
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
version: "3"
services:
    link-checker:
        image: identifiersorg/cloud-ws-link-checker:1.0.1
        environment:
            - WS_LINK_CHECKER_CONFIG_REDIS_HOST=redis
            - WS_LINK_CHECKER_CONFIG_BACKEND_SERVICE_RESOLVER_HOST=resolver
        ports:
            - "8084:8084"
        depends_on:
            - resolver
            - redis
    resolver:
        image: identifiersorg/cloud-ws-resolver:1.0.3
        environment:
            - WS_RESOLVER_CONFIG_REDIS_HOST=redis
            - WS_RESOLVER_CONFIG_REDIS_PORT=6379
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_HOST=recommender
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_PORT=8083
            - WS_RESOLVER_JVM_MEMORY_MAX=1024m
            - WS_RESOLVER_CONFIG_APPLICATION_ACTIVE_PROFILE=development
        ports:
            - "8080:8080"
        depends_on:
            - redis
    redis:
        image: redis:4.0.8-alpine
        ports:
            - "6379:6379"
